# Generated by Django 4.0.5 on 2022-07-15 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('W_fname', models.CharField(max_length=200)),
                ('W_lname', models.CharField(blank=True, max_length=200)),
                ('W_id', models.IntegerField(primary_key=True, serialize=False)),
                ('W_email', models.EmailField(blank=True, max_length=300, null=True)),
                ('W_category', models.CharField(max_length=200)),
                ('W_pin', models.IntegerField()),
                ('w_phno', models.IntegerField()),
                ('Rate_P_Hour', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_lname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_review', models.TextField()),
                ('U_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.customer')),
                ('W_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.worker')),
            ],
        ),
    ]
