# Generated by Django 4.0.5 on 2022-07-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_worker_alter_customer_c_lname_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='W_id',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='W_lname',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='W_pin',
        ),
        migrations.AddField(
            model_name='worker',
            name='W_company',
            field=models.CharField(default='company', max_length=20),
        ),
        migrations.AddField(
            model_name='worker',
            name='W_company_motto',
            field=models.CharField(default='motto', max_length=50),
        ),
        migrations.AddField(
            model_name='worker',
            name='W_desc',
            field=models.CharField(default='description', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='c_uid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='worker',
            name='W_email',
            field=models.EmailField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
