# Generated by Django 4.0.5 on 2022-07-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_customer_id_remove_worker_w_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='W_password',
            field=models.CharField(default='00000', max_length=20),
        ),
    ]
