# Generated by Django 4.0.5 on 2022-07-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_worker_w_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='c_uid',
            field=models.EmailField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='worker',
            name='W_password',
            field=models.CharField(max_length=20),
        ),
    ]
